# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CppGen < Formula
  desc "Modern C++ project generator with CMake, package managers, IDE configurations and development tools"
  homepage "https://github.com/matpdev/cpp-gen"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matpdev/cpp-gen/releases/download/v0.1.1/cpp-gen_0.1.1_darwin_amd64.tar.gz"
      sha256 "fc51317f077e1571fa65ba25fbd85cf1d9e1e97d0f86c2ddda9775587d13faf1"

      define_method(:install) do
        bin.install "cpp-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matpdev/cpp-gen/releases/download/v0.1.1/cpp-gen_0.1.1_darwin_arm64.tar.gz"
      sha256 "6e1cc1e819dad9718e7eaed6daf224cf024fb17321b32af5a58bf3621dfdf4aa"

      define_method(:install) do
        bin.install "cpp-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matpdev/cpp-gen/releases/download/v0.1.1/cpp-gen_0.1.1_linux_amd64.tar.gz"
      sha256 "0e577d4b74365697dee147d9b462330cbc2cd18727878850ccccf38a91a1a856"
      define_method(:install) do
        bin.install "cpp-gen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matpdev/cpp-gen/releases/download/v0.1.1/cpp-gen_0.1.1_linux_arm64.tar.gz"
      sha256 "594f73b8049c54cc275673fad37e9714d0a299c64b448200632a6319b5929e79"
      define_method(:install) do
        bin.install "cpp-gen"
      end
    end
  end

  test do
    system "#{bin}/cpp-gen", "--version"
  end
end
