# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CppGen < Formula
  desc "Modern C++ project generator with CMake, package managers, IDE configurations and development tools"
  homepage "https://github.com/matpdev/cpp-gen"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matpdev/cpp-gen/releases/download/v0.2.0/cpp-gen_0.2.0_darwin_amd64.tar.gz"
      sha256 "7c8ae3a17b4a4802757ae23cc504b05ddb9e1d41cff9527f0220adc3fadf6c43"

      define_method(:install) do
        bin.install "cpp-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matpdev/cpp-gen/releases/download/v0.2.0/cpp-gen_0.2.0_darwin_arm64.tar.gz"
      sha256 "a149780749e916103a0983a93267a18ebe4348744fde52999616b10868446e75"

      define_method(:install) do
        bin.install "cpp-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matpdev/cpp-gen/releases/download/v0.2.0/cpp-gen_0.2.0_linux_amd64.tar.gz"
      sha256 "accc005f65fe1d828e2d93bfd07cf17e8747c21e20990c848dba7aaecfa18cdc"
      define_method(:install) do
        bin.install "cpp-gen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matpdev/cpp-gen/releases/download/v0.2.0/cpp-gen_0.2.0_linux_arm64.tar.gz"
      sha256 "9f9538060fc1d47b7faf312346231ca5883d9755cb18f0b86b5a126ef315c7e0"
      define_method(:install) do
        bin.install "cpp-gen"
      end
    end
  end

  test do
    system "#{bin}/cpp-gen", "--version"
  end
end
